### ISSUE TITLE
Unable to run the Platooning simulation

### ISSUE THREAD

**Issue by saxenam06** [HarunTeper/AuNa#4]
Hello, Many Thanks for open sourcing your interesting work. I made an attempt to implement your repo, however I am unable to get things running. Request your kind help.
1. I could successfully build as below
![image](https://github.com/HarunTeper/AuNa/assets/83720464/0e7dc13e-7567-4872-bcb2-fe9549a1a0a4)
2. Gazebo launches successfully but without moving vehicles after I run _ros2 launch auna_scenarios scenario_platooning.launch.py_
![image](https://github.com/HarunTeper/AuNa/assets/83720464/5ea5120f-8b82-43f0-80f6-d2385fbf55ba)
3. After this step i fail to understand where to run the following command. Could you please help. 
_cmake --build build --target run_ros2_platooning_

**Comment by HarunTeper** [comment]
Hello,

sorry for your troubles with getting the simulation running. I hope to update the documentation in the following weeks.
After launching the simulation, you need to use Rviz to input your navigation goals using the tools in the tool bar of Rviz (you can see two Rviz windows, one for each robot on the side of your screen).

For building omnet++ and artery, you can follow the commands in the artery_auto_setup.sh and omnet_auto_setup.sh files.

After everything is installed, you need to run the following commands for the communication simulation:
(modify your paths according to your installation)

cd ~/AuNa
colcon build --symlink-install

After that, in one terminal, run the following commands
source ~/AuNa/install/setup.bash
cd ~/artery-ros2
cmake --build build --target run_ros2_platooning

**Comment by HarunTeper** [comment]
Hello,

after running the setup scripts, the following commands should launch everything needed for platooning:

Terminal 1:

cd AuNa
source install/setup.bash
ros2 launch auna_scenarios scenario_platooning.launch.py 
After that, you can use the rviz window to separately control the vehicles. However, for platooning, you only need to control the first vehicle via the rviz window. You should first start OMNeT++ and Artery before telling the first vehicle to move.

Terminal 2

source AuNa/install/setup.bash
cd artery-ros2
cmake --build build --target run_ros2_platooning

If you dont have a build directory in /artery-ros2, you need to execute the commands in the artery_auto_setup.sh file (maybe manually if you have a different path).

After OMNeT++ launched, you need to run it using the "Fast" icon in the top left toolbar.

After that, you can tell the first vehicle in the platoon to move to a location in Rviz, and the second vehicle should follow it.

**Comment by saxenam06** [comment]
Yes, Thank You, It works now.
